# Generated by Django 6.0 on 2026-01-15 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo_perfil',
            field=models.CharField(choices=[('professor', 'Professor'), ('coordenador', 'Coordenador')], default='professor', max_length=20),
        ),
    ]
